### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by OKJINHAE** [yfeng95/DECA#168]
I get the following error:
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

I AM looking forward to your reply 
Thank you..

**Comment by elizabethjcobs** [comment]
i am having this issue too

**Comment by MilesTheProwler** [comment]
did you solve it ?
