### ISSUE TITLE
Now validation

### ISSUE THREAD

**Issue by daladulu** [yfeng95/DECA#173]
Sorry, I evaluate DECA on Now validation, but I got the result like median: 6.6358, mean: 17.92029, std: 22.8113.
I just used [this code](https://github.com/soubhiksanyal/now_evaluation), and run compute_error.py to get _computed_distances.npy.
And then, 
`errors = np.load('_computed_distances.npy', allow_pickle=True, encoding="latin1").item()['computed_distances']
median = np.median(np.hstack(errors))
mean = np.mean(np.hstack(errors))
std = np.std(np.hstack(errors))`
I'm not quite sure which part is wrong. Hope someone can help me... Thank you so much.

**Comment by daladulu** [comment]
Besides, I also get the result like: 
![image](https://user-images.githubusercontent.com/50403079/218634162-22ea5a81-5eb2-4ba7-89ef-c5108ea16222.png)
![image](https://user-images.githubusercontent.com/50403079/218634256-05bff981-ed98-42c0-b8b6-43fed86e47a5.png)
Does anyone have the same problem?

**Comment by daladulu** [comment]
[#52](https://github.com/yfeng95/DECA/issues/52)

**Comment by tongmd** [comment]
Hello, have u solved the problem. I also get the same median value and I use FAN as the detector @daladulu

**Comment by daladulu** [comment]
Hi, About the `median`, 
`codedict = self.deca.encode(images)
 codedict['exp'][:] = 0.
 codedict['pose'][:] = 0.
 opdict, visdict = self.deca.decode(codedict)`, 
I didn't set the 'exp' and 'pose' to be '0' that why I got the median value. 
The landmark problem, you can see [https://github.com/yfeng95/DECA/issues/52](url).
And I change the cropping scale to 1.25. @the-star-sea

**Comment by tongmd** [comment]
> Hi, About the `median`, `codedict = self.deca.encode(images) codedict['exp'][:] = 0. codedict['pose'][:] = 0. opdict, visdict = self.deca.decode(codedict)`, I didn't set the 'exp' and 'pose' to be '0' that why I got the median value. The landmark problem, you can see [https://github.com/yfeng95/DECA/issues/52](url). And I change the cropping scale to 1.25. @the-star-sea

Thank u! I have solved the problem. It is because of the index of landmark.

**Comment by prokaryote-hgy** [comment]
@daladulu Hi, what's your results now? I got the results of median 1.32, mean 1.67, std 1.42, I don't know what's wrong.

**Comment by daladulu** [comment]
> @daladulu Hi, what's your results now? I got the results of median 1.32, mean 1.67, std 1.42, I don't know what's wrong.

In the DECA paper, they mentioned "The reconstruction errors are, median: 1.18/1.19 (coarse / detailed), mean: 1.46/1.47 (coarse / detailed), std: 1.25/1.25 (coarse / detailed)."  I got the errors are median: 1.23, mean: 1.53, std: 1.29. @prokaryote-hgy

**Comment by prokaryote-hgy** [comment]
@daladulu Thank you for your reply! I have a few more questions about the training step. Your insights would be greatly appreciated. Kindly take a moment to review and respond to the following queries:

1. Did you use the default traning settings? 
2. Did you undergo pretraining on your own or use the author's provided release model as a pretrained model? 
3. Did you perform landmark cleaning? 
4. How many images did you select for training from VGGFace2 and BUPT-Balancedface datasets, respectively?

Thank you in advance for your time and assistance. I'm looking forward to hearing from you soon.

**Comment by daladulu** [comment]
@prokaryote-hgy 1. No, I trained on my dataset and changed the setting. 2. I used my own dataset, so I pretrained the model on my dataset. 3. Acturally, I didn't understand how to do the data cleaning. (If you are clear about data cleaning, please share with me your understanding ^_^) 4. my own dataset, so...

**Comment by emlcpfx** [comment]
@daladulu @prokaryote-hgy 
How long does it take to retrain the DECA model?

Have you tried retraining using dlib or SPIGA as the landmark detector instead of FAN? This would give better eye alignment results. I’d like to do this myself, but I really don’t know how.
